### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Frzifus** [Dax89/REDasm#2]
Wanted to download and test REDasm right now. But how do I compile it?

**Comment by Dax89** [comment]
I have added an "How to compile" section in README 👍

**Comment by Frzifus** [comment]
Oh, i seem blind..

**Comment by pfalcon** [comment]
So, following that section, which is literally:

~~~
cd REDasm
qmake && make
~~~

I get "Project ERROR: Unknown module(s) in QT: webengine webenginewidgets". Majority of users would stop here and go back to watch TV ;-). And that's lost contributors ;-).

**Comment by frzifus** [comment]
i guess you are missing webenginewidgets? :octocat: 

have you tried to compile with docker?

**Comment by pfalcon** [comment]
Yep, no worries. Continuation of this (absolutely typical to most C++/Qt projects) issue in https://github.com/REDasmOrg/REDasm/issues/6
